using FluentAssertions;
using PatryCloset.Domain.Common;

namespace PatryCloset.UnitTests.Domain.Entities;

public class BaseEntityTests
{
    // Concrete subclass to test abstract BaseEntity
    private class TestEntity : BaseEntity { }

    private class TestDomainEvent : DomainEvent { }

    [Fact]
    public void Id_ShouldBeAutoGenerated_AndNotEmpty()
    {
        var entity = new TestEntity();

        entity.Id.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void Id_TwoInstances_ShouldHaveDifferentIds()
    {
        var entity1 = new TestEntity();
        var entity2 = new TestEntity();

        entity1.Id.Should().NotBe(entity2.Id);
    }

    [Fact]
    public void AddDomainEvent_ShouldAddEventToDomainEvents()
    {
        var entity = new TestEntity();
        var domainEvent = new TestDomainEvent();

        entity.AddDomainEvent(domainEvent);

        entity.DomainEvents.Should().HaveCount(1);
        entity.DomainEvents.Should().Contain(domainEvent);
    }

    [Fact]
    public void RemoveDomainEvent_ShouldRemoveSpecificEvent()
    {
        var entity = new TestEntity();
        var event1 = new TestDomainEvent();
        var event2 = new TestDomainEvent();
        entity.AddDomainEvent(event1);
        entity.AddDomainEvent(event2);

        entity.RemoveDomainEvent(event1);

        entity.DomainEvents.Should().HaveCount(1);
        entity.DomainEvents.Should().Contain(event2);
        entity.DomainEvents.Should().NotContain(event1);
    }

    [Fact]
    public void ClearDomainEvents_ShouldEmptyCollection()
    {
        var entity = new TestEntity();
        entity.AddDomainEvent(new TestDomainEvent());
        entity.AddDomainEvent(new TestDomainEvent());

        entity.ClearDomainEvents();

        entity.DomainEvents.Should().BeEmpty();
    }

    [Fact]
    public void DomainEvents_ShouldReturnReadOnlyCollection()
    {
        var entity = new TestEntity();

        entity.DomainEvents.Should().BeAssignableTo<IReadOnlyCollection<DomainEvent>>();
    }
}
